version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mpesa_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mpesa
      MYSQL_USER: mpesa
      MYSQL_PASSWORD: password
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mpesa_network
  mpesatinker: 
   image: mpesatinker:latest
   entrypoint: ["sh", "-c", "sleep 50 && /app/mpesa"]
   depends_on:
     - mysql
   container_name: mpesa_tinker
   ports:
      - '8080:8080'
   volumes:
     - ./.env.docker:/app/.env
   networks:
    - mpesa_network

volumes:
  mysql_data:

networks:
  mpesa_network:
    driver: bridge
